name: CI - Deploy to RoviSoft.

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Clean the uploaded files
        run: |
          mv ./release/latest/ProgrammingGroundUp.html ./release/latest/index.html && \
          rm -f /release/latest/ProgrammingGroundUp*

      - name: Upload via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: "./release/latest/"
          delete: "true"
