name: CI - Deploy to RoviSoft

on:
  workflow_run:
    workflows: [ "CI - Release books" ]
    branches: [ main ]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Clean the uploaded files
        run: |
          mv ./release/latest/ProgrammingGroundUp.html ./release/latest/index.html && \
          rm -f ./release/latest/ProgrammingGroundUp*

      - name: Upload via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: "./release/latest/"
          delete: "true"
