name: CI - Release books.

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Execute the release script
        run: echo Hello, world!

      - name: Show directory
        run: ls -lhaR ./
