name: CI - Release books.

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run release script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          ls -lhaR ./,
          echo test, and deploy your project.
