name: CI - Release books.

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Execute the release script
        run: |
          whereis wget && \
          whereis curl && \
          sudo apt-get install wget && \
          wget https://github.com/jgm/pandoc/releases/download/2.11.2/pandoc-2.11.2-1-amd64.deb && \
          sudo dpkg -i pandoc-2.11.2-1-amd64.deb && \
          ls -lha . && \
          rm -f pandoc-1.19.2.1-1-amd64.deb && \
          pandoc -v && \
          cd ./src/programming-from-the-ground-up && \
          ./make.sh && \
          git diff
