name: CI - Release books.

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

#      - name: Execute the release script
#        run: cd ./src/programming-from-the-ground-up && ./make.sh

      - name: Show directory
        run: sudo apt-get install pandoc && pandoc -v
