name: CI - Release books

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  build:
    env:
      PACKAGES_HOME: "/home/runner/cache-linux/"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache-packages
        with:
          path: /home/runner/cache-linux/
          key: ${{ runner.os }}-cache-packages-v1.33

      - name: Install packages
        if: steps.cache-packages.outputs.cache-hit != 'true'
        run: |
          SOURCE=${HOME}/cache-linux
          echo "# --------------------------------------------------------"
          echo "# Where am I?"
          pwd
          echo "HOME: ${HOME}"
          echo "SOURCE: ${SOURCE}"
          #sed -i "s/mesg n || true/test -t 0 \&\& mesg n || true/" /root/.profile
          echo "# --------------------------------------------------------"
          echo "# APT update"
          sudo apt update
          echo "# --------------------------------------------------------"
          echo "# Set up snapshot"
          mkdir -p "${HOME}"/snapshots/
          echo "# --------------------------------------------------------"
          echo "# Install tools"
          sudo rm -f /var/lib/apt/lists/lock
          sudo apt install -y backintime-common vim bash-completion
          echo "# --------------------------------------------------------"
          echo "# Take the first snapshot"
          sudo find / -type f,l > "${HOME}"/snapshots/snapshot_01.txt 2> /dev/null
          echo "# --------------------------------------------------------"
          echo "# Install pandoc and dependencies"
          sudo apt install -y texlive-latex-extra wget
          wget -q https://github.com/jgm/pandoc/releases/download/2.11.2/pandoc-2.11.2-1-amd64.deb
          sudo dpkg -i pandoc-2.11.2-1-amd64.deb
          rm -f pandoc-2.11.2-1-amd64.deb
          echo "# --------------------------------------------------------"
          echo "# Take second snapshot"
          sudo find / -type f,l > "${HOME}"/snapshots/snapshot_02.txt 2> /dev/null
          echo "# --------------------------------------------------------"
          echo "# Filter new files"
          diff -C 1 \
          --color=always \
          "${HOME}"/snapshots/snapshot_01.txt "${HOME}"/snapshots/snapshot_02.txt \
          | grep -E "^\+" \
          | sed -E s/..// \
          > "${HOME}"/snapshots/snapshot_new_files.txt
          < "${HOME}"/snapshots/snapshot_new_files.txt wc -l
          ls -lha "${HOME}"/snapshots/
          echo "# --------------------------------------------------------"
          echo "# Make cache directory"
          rm -fR "${SOURCE}"
          mkdir -p "${SOURCE}"
          while IFS= read -r LINE
          do
            sudo cp -a --parent "${LINE}" "${SOURCE}"
          done < "${HOME}"/snapshots/snapshot_new_files.txt
          ls -lha "${SOURCE}"
          echo ""
          sudo du -sh "${SOURCE}"
          echo "# --------------------------------------------------------"

      - name: Copy cached packages
        if: steps.cache-packages.outputs.cache-hit == 'true'
        run: |
          echo "# --------------------------------------------------------"
          echo "# Using Cached packages"
          ls -lha /home/runner/cache-linux/
          sudo cp --force --recursive /home/runner/cache-linux/. /
          echo "# --------------------------------------------------------"

      - name: Generate release files and commit in GitHub
        run: |
          echo "# --------------------------------------------------------"
          echo "# Generating release files"
          cd ./src/programming-from-the-ground-up
          ./make.sh
          cd ../../
          git config --global user.name 'Israel Roldan'
          git config --global user.email 'israel.alberto.rv@gmail.com'
          git add .
          git status
          ls -lha release/
          echo "# --------------------------------------------------------"
#          cd ./src/programming-from-the-ground-up
#          ./make.sh
#          cd ../../
#          git config --global user.name 'Israel Roldan'
#          git config --global user.email 'israel.alberto.rv@gmail.com'
#          git add .
#          git commit -m "Automated Release."
#          git push
