name: CI - Release books

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  build:
    env:
      PACKAGES_HOME: "$HOME/packages"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Cache packages
        uses: actions/cache@v2
        id: cache-packages
        with:
          path: "${{env.PACKAGES_HOME}}"

      - name: Install packages
        env:
          CACHE_EXISTS: "${{steps.cache-packages.outputs.cache-hit}}"
        run: |
          if [[ "$CACHE_EXISTS" == 'true' ]]; then
            echo "Using Cached packages"
          else
            echo "Install packages"
            sudo apt-get install -y texlive-latex-extra && \
            wget https://github.com/jgm/pandoc/releases/download/2.11.2/pandoc-2.11.2-1-amd64.deb && \
            sudo dpkg -i pandoc-2.11.2-1-amd64.deb && \
            rm -f pandoc-2.11.2-1-amd64.deb
          fi
          echo "--------------------------------------------------------"
          echo "steps.cache-packages.outputs.cache-hit: ${{steps.cache-packages.outputs.cache-hit}}"
          echo "--------------------------------------------------------"
#          echo "steps.cache-packages.outputs: ${{steps.cache-packages.outputs}}"
#          echo "--------------------------------------------------------"
#          echo "steps.cache-packages: ${{steps.cache-packages}}"
#          echo "--------------------------------------------------------"
#          echo "steps: ${{steps}}"
#          echo "--------------------------------------------------------"
#          echo "env.PACKAGES_HOME: ${{env.PACKAGES_HOME}}"
#          echo "--------------------------------------------------------"
#          echo "env: ${{env}}"
#          echo "--------------------------------------------------------"
#          ls -lhaR ${{env.PACKAGES_HOME}}"
#          echo "--------------------------------------------------------"

#          echo "::add-path::$PACKAGES_HOME/bin"

#          sudo apt-get update
#          curl -sSL "$VALGRIND_SOURCE" -o - | tar -xjv --one-top-level=packages --strip-components=1
#          cd packages
#          ./configure --prefix="$PACKAGES_HOME"
#          make -j
#          make install

#      - name: Install packages
#        if: steps.cache.outputs.cache-hit != 'true'
#        run: |
#          sudo apt-get install -y texlive-latex-extra && \
#          wget https://github.com/jgm/pandoc/releases/download/2.11.2/pandoc-2.11.2-1-amd64.deb && \
#          sudo dpkg -i pandoc-2.11.2-1-amd64.deb && \
#          rm -f pandoc-2.11.2-1-amd64.deb

      - name: Generate release files and commit in GitHub
        run: |
          cd ./src/programming-from-the-ground-up && \
          ./make.sh && \
          cd ../../ && \
          git config --global user.name 'Israel Roldan' && \
          git config --global user.email 'israel.alberto.rv@gmail.com' && \
          git add . && \
          git commit -m "Automated Release." && \
          git push
