name: CI - Release books.

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Execute the release script
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.11.2/pandoc-2.11.2-1-amd64.deb && \
          sudo dpkg -i pandoc-2.11.2-1-amd64.deb && \
          rm -f pandoc-2.11.2-1-amd64.deb && \
          sudo apt-get install -y texlive-latex-extra && \
          pandoc -v && \
          cd ./src/programming-from-the-ground-up && \
          ./make.sh && \
          cd ../../ && \
          git config --global user.name 'Israel Roldan' && \
          git config --global user.email 'israel.alberto.rv@gmail.com' && \
          git diff . && \
          git add . && \
          git commit -m "Automated Release." && \
          git status && \
          git push
